// <auto-generated />
using System;
using Human_Resource_Generator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Human_Resource_Generator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230316071252_ManyToManyAdded")]
    partial class ManyToManyAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Human_Resource_Generator.Models.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_id"), 1L, 1);

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("employee_department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employee_id");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.Employee_Training", b =>
                {
                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<int>("program_id")
                        .HasColumnType("int");

                    b.Property<string>("program_manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employee_id");

                    b.HasIndex("program_id");

                    b.ToTable("employees_Training");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.Training_program", b =>
                {
                    b.Property<int>("program_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("program_id"), 1L, 1);

                    b.Property<DateTime>("date_of_program")
                        .HasColumnType("datetime2");

                    b.Property<string>("program_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("program_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("program_id");

                    b.ToTable("training_Program");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.Employee_Training", b =>
                {
                    b.HasOne("Human_Resource_Generator.Models.Employee", "employee")
                        .WithMany("employees_Training")
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Human_Resource_Generator.Models.Training_program", "training_Program")
                        .WithMany("employees_Training")
                        .HasForeignKey("program_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("training_Program");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.Employee", b =>
                {
                    b.Navigation("employees_Training");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.Training_program", b =>
                {
                    b.Navigation("employees_Training");
                });
#pragma warning restore 612, 618
        }
    }
}
