// <auto-generated />
using System;
using Human_Resource_Generator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Human_Resource_Generator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230316144644_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Human_Resource_Generator.Models.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_id"), 1L, 1);

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("employee_department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employee_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.EmployeeTraining", b =>
                {
                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<int>("program_id")
                        .HasColumnType("int");

                    b.HasKey("employee_id", "program_id");

                    b.HasIndex("program_id");

                    b.ToTable("EmployeeTrainings");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.TrainingProgram", b =>
                {
                    b.Property<int>("program_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("program_id"), 1L, 1);

                    b.Property<DateTime>("date_of_program")
                        .HasColumnType("datetime2");

                    b.Property<string>("program_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("program_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("program_id");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.EmployeeTraining", b =>
                {
                    b.HasOne("Human_Resource_Generator.Models.Employee", "Employee")
                        .WithMany("Training_programs")
                        .HasForeignKey("program_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Human_Resource_Generator.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("employees")
                        .HasForeignKey("program_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.Employee", b =>
                {
                    b.Navigation("Training_programs");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.TrainingProgram", b =>
                {
                    b.Navigation("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
