// <auto-generated />
using System;
using Human_Resource_Generator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Human_Resource_Generator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Human_Resource_Generator.Models.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_id"), 1L, 1);

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("employee_department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employee_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.EmployeeTraining", b =>
                {
                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<int>("program_id")
                        .HasColumnType("int");

                    b.HasKey("employee_id", "program_id");

                    b.HasIndex("program_id");

                    b.ToTable("EmployeeTrainings");
                });

            modelBuilder.Entity("Human_Resource_Generator.Models.TrainingProgram", b =>
                {
                    b.Property<int>("program_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("program_id"), 1L, 1);

                    b.Property<DateTime>("date_of_program")
                        .HasColumnType("datetime2");

                    b.Property<string>("program_manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("program_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("program_result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("training_date")
                        .HasColumnType("datetime2");

                    b.HasKey("program_id");

                    b.ToTable("employee_Training");
                });
#pragma warning restore 612, 618
        }
    }
}
